### ISSUE TITLE
你好，我运行命令报错啦

### ISSUE THREAD

**Issue by Maxiaochuan123** [eyelly-wu/i18n-pro#1]
![image](https://user-images.githubusercontent.com/25688141/191041319-0f5a6dbe-904a-470a-b867-c204d4449654.png)

**Comment by eyelly-wu** [comment]
麻烦提供下以下版本信息：
node：
npm：
操作系统：

**Comment by Maxiaochuan123** [comment]
node: v16.17.0
npm: 8.15.0
system: windows10 64

**Comment by eyelly-wu** [comment]
@Maxiaochuan123 尝试修复了

**Comment by Maxiaochuan123** [comment]
是的可以执行命令了， 我想要在 vite + vue 中使用，运行命令后似乎没有正确生成翻译文件，默认配置我没有修改，请问我需要怎样配置呢，如果方便解答的话，谢谢~
![image](https://user-images.githubusercontent.com/25688141/191986813-4db38eee-3843-4d5a-96f4-409aafb95d75.png)
![image](https://user-images.githubusercontent.com/25688141/191987039-cc2d86e2-25d0-414f-a342-0832d5d77adc.png)
![image](https://user-images.githubusercontent.com/25688141/191987225-f1a2b6da-a78e-4aee-961d-f01ed385c341.png)
![image](https://user-images.githubusercontent.com/25688141/191987263-968359d7-7b4d-43f3-ad9d-e3adcfded707.png)

**Comment by eyelly-wu** [comment]
看样子应该是正则没有匹配到文件，你需要调整下配置文件中 `fileRegExp` 这个属性的配置

**Comment by Maxiaochuan123** [comment]
确实是正则这里需要重新写，请问是否考虑用路径替代正则呢， 这样似乎方便些
类似 i18next-scanner 这个包中的  input 配置项他是这样的 'src/**/*.{js,jsx,vue}'

**Comment by Maxiaochuan123** [comment]
您的这款 插件非常棒，当初我寻找了很多解决方案，使用 i18next-scanner 进行文件扫描匹配翻译成 crc 码的方式，但不理想需要手动将生成的语言 json 文件，手动粘贴翻译后再粘贴回来，您的想法和我不谋而合，我也想着要是能掉 api 自动翻译就好了，非常幸运看到了您的项目，太棒了！

**Comment by Maxiaochuan123** [comment]
![image](https://user-images.githubusercontent.com/25688141/192096944-795000a5-93d3-461b-8f69-3a6c20e53406.png)

.log 文件夹 以及生成的语言空文件夹 .jso 能去掉吗？我看您提供的例子 https://codesandbox.io/p/github/eyelly-wu/i18n-pro-react-demo/main?file=%2Fsrc%2FApp.tsx
中 i18n 文件夹中只有语言.json 文件非常干净~

**Comment by eyelly-wu** [comment]
哈哈，为了便于沟通，诚邀你加入i18n-pro的QQ群：251644053

**Comment by eyelly-wu** [comment]
@Maxiaochuan123 嘿，老兄，感谢一直以来对 `i18n-pro` 的支持，告诉你个好消息，目前已正式推出了适配 `Vue` 的版本，欢迎体验尝试
- [Vue 3](https://github.com/i18n-pro/vue)
- [Vue 2](https://github.com/i18n-pro/vue2)
