### ISSUE TITLE
这个是帮助开发过程生成 语言包吗？

### ISSUE THREAD

**Issue by zhang1446802857** [eyelly-wu/i18n-pro#3]
刚接触这个，感觉语言包要自己手写，就很烦。想着是否可以自动翻译。

**Comment by eyelly-wu** [comment]
@zhang1446802857 是的，本库主打的特性就是自动提前翻译文案，并利用第三方翻译平台翻译文案，最终生成语言包文件。可以说整个开发过程体验是非常好的，当前库的英文版文档，就是这样生成的。想了解更多可以多看看本库的文档，希望可以帮助到你
