### ISSUE TITLE
文件扫描支持数组和通配符

### ISSUE THREAD

**Issue by ghost** [eyelly-wu/i18n-pro#4]
有些项目多文件夹位于项目根目录，不在src等子目录下面，直接写根目录地址会把node_modules或者其他无关目录扫描进去。

所以文件扫描希望entry和fileRegExp合并成支持数组和通配符的形式，类似tailwindcss，
```
["./components/**/*.{ts,vue}", "./pages/**/*.{ts,vue}"]
```

建议使用glob

https://www.npmjs.com/package/glob

**Comment by eyelly-wu** [comment]
@lulucas 之前有个哥们提过类似的需求，当时没 get 到他点，现在理解了。感谢你的提议，该特性会在近期得以支持，敬请期待

**Comment by eyelly-wu** [comment]
@lulucas 嘿，老兄，在 v2.1.0 中已添加通过配置 `input` 属性来支持 `glob` 语法来过滤文件，欢迎尝试
